### ISSUE TITLE
Undefined behaviour in Array::sliced_op

### ISSUE THREAD

**Issue by jasonyu1996** [patricksongzy/corgi#2]
**Describe the bug**
Hi! `Array::sliced_op` saves pointers to the content of `arrays` in vectors:
https://github.com/patricksongzy/corgi/blob/77568136ef2df299f4f4e5a9167042d144118e49/src/array/mod.rs#L528-L546

Those pointers are subsequently used to perform mutations:
https://github.com/patricksongzy/corgi/blob/77568136ef2df299f4f4e5a9167042d144118e49/src/array/mod.rs#L593
https://github.com/patricksongzy/corgi/blob/77568136ef2df299f4f4e5a9167042d144118e49/src/array/mod.rs#L603-L604

This is an undefined behaviour and may lead to miscompilation.

**To Reproduce**
MIRI reports this issue when running the `array::tests::test_backward_dimensions` test case. It is necessary to comment out the mimalloc lines to make MIRI run though because it does not support FFI.

https://github.com/patricksongzy/corgi/blob/77568136ef2df299f4f4e5a9167042d144118e49/src/lib.rs#L32-L33

**Versions Affected**
0.9.9

**Expected behavior**
MIRI should not report any undefined behaviour.

**System Details**
 - OS: Ubuntu
 - Version: 22.04.5 LTS
 - Processor Family: amd64

**Additional context**
A simplified mini demo of this issue: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=76c5f934889cbccf0101ffcef2734ae0

Run with MIRI and it will report the issue.

**Comment by patricksongzy** [comment]
Hi!

Thanks for the detailed report :). It looks like this was the result of an unnecessary "optimisation" I made (iirc to do w disjoint accesses or smth); I've rebased onto the previous safe version. I've also feature-gated the allocator change.
I recall wanting to undo the changes regardless, so this works out well. TBH, I've never been a huge fan of the implementations of `sliced_op` and `element_wise_op`. Broadcasting in general feels icky.

Should be no remaining unsafe code in the repo. MIRI seems quite pleased as well (tested w 2024-09-01 nightly-musl on x64 void). Disabled on some tests which run at potato speed.

Thanks!
